name: unpack bootimg

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      IMG_URL:
        description: 'IMG_URL'
        required: true
        default: 'https://github.com/mediateeee/action_mkbootimg/raw/main/boot.img'
      IMG_NAME:
        description: 'IMG_NAME'
        required: true
        default: 'boot'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python3 python3-pip cpio wget android-tools-mkbootimg abootimg
    
    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var

    - name: Download your files
      run: |
        wget ${{ github.event.inputs.IMG_URL }}

    - name: Start making
      run: |
        abootimg -x "${{ github.event.inputs.IMG_URL }}.img"

    - name: Rename initrd.img
      run: |
        mv initrd.img ramdisk.img

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./kernel
          ./ramdisk.img
        name: My_Unpacked_Bootimg-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: My unpacked bootimg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
