name: action mkbootimg

on:
  workflow_dispatch:
    inputs:
      KERNEL_URL:
        description: 'KERNEL_URL'
        required: true
        default: 'https://github.com/mediateeee/action_mkbootimg/raw/main/kernel'
      RAMDISK_URL:
        description: 'RADMISK_URL'
        required: true
        default: 'https://github.com/mediateeee/action_mkbootimg/raw/main/ramdisk.img'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python3 python3-pip cpio wget android-tools-mkbootimg abootimg
    
    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var

    - name: Download your files
      run: |
        wget ${{ github.event.inputs.KERNEL_URL }}
        wget ${{ github.event.inputs.RAMDISK_URL }}

    - name: Start making
      run: |
        mkbootimg --kernel kernel --ramdisk ramdisk.img -o boot.img 

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./boot.img
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Made boot.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
